CREATE TABLE IF NOT EXISTS vyapar_cards (
  id SERIAL PRIMARY KEY,
  ubid VARCHAR(32) NOT NULL,
  serial VARCHAR(32) UNIQUE NOT NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP,
  qr_payload JSONB
);
CREATE TABLE IF NOT EXISTS delegates (
  id SERIAL PRIMARY KEY,
  delegate_id VARCHAR(32) UNIQUE NOT NULL,
  ubid VARCHAR(32) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(64) NOT NULL,
  scopes JSONB NOT NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS field_visits (
  id SERIAL PRIMARY KEY,
  visit_id VARCHAR(32) UNIQUE NOT NULL,
  ubid VARCHAR(32) NOT NULL,
  officer_id VARCHAR(64) NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  captured_at TIMESTAMP NOT NULL DEFAULT NOW(),
  within_premises BOOLEAN NOT NULL DEFAULT FALSE,
  notes VARCHAR(1024),
  photo_count INT DEFAULT 0
);
