/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GovRouteImport } from './routes/gov'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GovIndexRouteImport } from './routes/gov.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as GovReviewRouteImport } from './routes/gov.review'
import { Route as GovQueryRouteImport } from './routes/gov.query'
import { Route as GovMapRouteImport } from './routes/gov.map'
import { Route as GovLivelinkRouteImport } from './routes/gov.livelink'
import { Route as GovBusinessesRouteImport } from './routes/gov.businesses'
import { Route as GovAuditRouteImport } from './routes/gov.audit'
import { Route as GovAlertsRouteImport } from './routes/gov.alerts'
import { Route as BusinessSubmitRouteImport } from './routes/business.submit'
import { Route as BusinessNoticesRouteImport } from './routes/business.notices'
import { Route as BusinessLivelinkRouteImport } from './routes/business.livelink'
import { Route as BusinessHistoryRouteImport } from './routes/business.history'
import { Route as BusinessCardRouteImport } from './routes/business.card'
import { Route as GovBusinessesUbidRouteImport } from './routes/gov.businesses.$ubid'

const GovRoute = GovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovIndexRoute = GovIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const GovReviewRoute = GovReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => GovRoute,
} as any)
const GovQueryRoute = GovQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => GovRoute,
} as any)
const GovMapRoute = GovMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => GovRoute,
} as any)
const GovLivelinkRoute = GovLivelinkRouteImport.update({
  id: '/livelink',
  path: '/livelink',
  getParentRoute: () => GovRoute,
} as any)
const GovBusinessesRoute = GovBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => GovRoute,
} as any)
const GovAuditRoute = GovAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => GovRoute,
} as any)
const GovAlertsRoute = GovAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => GovRoute,
} as any)
const BusinessSubmitRoute = BusinessSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessNoticesRoute = BusinessNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessLivelinkRoute = BusinessLivelinkRouteImport.update({
  id: '/livelink',
  path: '/livelink',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessHistoryRoute = BusinessHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCardRoute = BusinessCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => BusinessRoute,
} as any)
const GovBusinessesUbidRoute = GovBusinessesUbidRouteImport.update({
  id: '/$ubid',
  path: '/$ubid',
  getParentRoute: () => GovBusinessesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/gov': typeof GovRouteWithChildren
  '/business/card': typeof BusinessCardRoute
  '/business/history': typeof BusinessHistoryRoute
  '/business/livelink': typeof BusinessLivelinkRoute
  '/business/notices': typeof BusinessNoticesRoute
  '/business/submit': typeof BusinessSubmitRoute
  '/gov/alerts': typeof GovAlertsRoute
  '/gov/audit': typeof GovAuditRoute
  '/gov/businesses': typeof GovBusinessesRouteWithChildren
  '/gov/livelink': typeof GovLivelinkRoute
  '/gov/map': typeof GovMapRoute
  '/gov/query': typeof GovQueryRoute
  '/gov/review': typeof GovReviewRoute
  '/business/': typeof BusinessIndexRoute
  '/gov/': typeof GovIndexRoute
  '/gov/businesses/$ubid': typeof GovBusinessesUbidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business/card': typeof BusinessCardRoute
  '/business/history': typeof BusinessHistoryRoute
  '/business/livelink': typeof BusinessLivelinkRoute
  '/business/notices': typeof BusinessNoticesRoute
  '/business/submit': typeof BusinessSubmitRoute
  '/gov/alerts': typeof GovAlertsRoute
  '/gov/audit': typeof GovAuditRoute
  '/gov/businesses': typeof GovBusinessesRouteWithChildren
  '/gov/livelink': typeof GovLivelinkRoute
  '/gov/map': typeof GovMapRoute
  '/gov/query': typeof GovQueryRoute
  '/gov/review': typeof GovReviewRoute
  '/business': typeof BusinessIndexRoute
  '/gov': typeof GovIndexRoute
  '/gov/businesses/$ubid': typeof GovBusinessesUbidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/gov': typeof GovRouteWithChildren
  '/business/card': typeof BusinessCardRoute
  '/business/history': typeof BusinessHistoryRoute
  '/business/livelink': typeof BusinessLivelinkRoute
  '/business/notices': typeof BusinessNoticesRoute
  '/business/submit': typeof BusinessSubmitRoute
  '/gov/alerts': typeof GovAlertsRoute
  '/gov/audit': typeof GovAuditRoute
  '/gov/businesses': typeof GovBusinessesRouteWithChildren
  '/gov/livelink': typeof GovLivelinkRoute
  '/gov/map': typeof GovMapRoute
  '/gov/query': typeof GovQueryRoute
  '/gov/review': typeof GovReviewRoute
  '/business/': typeof BusinessIndexRoute
  '/gov/': typeof GovIndexRoute
  '/gov/businesses/$ubid': typeof GovBusinessesUbidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/gov'
    | '/business/card'
    | '/business/history'
    | '/business/livelink'
    | '/business/notices'
    | '/business/submit'
    | '/gov/alerts'
    | '/gov/audit'
    | '/gov/businesses'
    | '/gov/livelink'
    | '/gov/map'
    | '/gov/query'
    | '/gov/review'
    | '/business/'
    | '/gov/'
    | '/gov/businesses/$ubid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business/card'
    | '/business/history'
    | '/business/livelink'
    | '/business/notices'
    | '/business/submit'
    | '/gov/alerts'
    | '/gov/audit'
    | '/gov/businesses'
    | '/gov/livelink'
    | '/gov/map'
    | '/gov/query'
    | '/gov/review'
    | '/business'
    | '/gov'
    | '/gov/businesses/$ubid'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/gov'
    | '/business/card'
    | '/business/history'
    | '/business/livelink'
    | '/business/notices'
    | '/business/submit'
    | '/gov/alerts'
    | '/gov/audit'
    | '/gov/businesses'
    | '/gov/livelink'
    | '/gov/map'
    | '/gov/query'
    | '/gov/review'
    | '/business/'
    | '/gov/'
    | '/gov/businesses/$ubid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  GovRoute: typeof GovRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gov': {
      id: '/gov'
      path: '/gov'
      fullPath: '/gov'
      preLoaderRoute: typeof GovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/': {
      id: '/gov/'
      path: '/'
      fullPath: '/gov/'
      preLoaderRoute: typeof GovIndexRouteImport
      parentRoute: typeof GovRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/gov/review': {
      id: '/gov/review'
      path: '/review'
      fullPath: '/gov/review'
      preLoaderRoute: typeof GovReviewRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/query': {
      id: '/gov/query'
      path: '/query'
      fullPath: '/gov/query'
      preLoaderRoute: typeof GovQueryRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/map': {
      id: '/gov/map'
      path: '/map'
      fullPath: '/gov/map'
      preLoaderRoute: typeof GovMapRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/livelink': {
      id: '/gov/livelink'
      path: '/livelink'
      fullPath: '/gov/livelink'
      preLoaderRoute: typeof GovLivelinkRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/businesses': {
      id: '/gov/businesses'
      path: '/businesses'
      fullPath: '/gov/businesses'
      preLoaderRoute: typeof GovBusinessesRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/audit': {
      id: '/gov/audit'
      path: '/audit'
      fullPath: '/gov/audit'
      preLoaderRoute: typeof GovAuditRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/alerts': {
      id: '/gov/alerts'
      path: '/alerts'
      fullPath: '/gov/alerts'
      preLoaderRoute: typeof GovAlertsRouteImport
      parentRoute: typeof GovRoute
    }
    '/business/submit': {
      id: '/business/submit'
      path: '/submit'
      fullPath: '/business/submit'
      preLoaderRoute: typeof BusinessSubmitRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/notices': {
      id: '/business/notices'
      path: '/notices'
      fullPath: '/business/notices'
      preLoaderRoute: typeof BusinessNoticesRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/livelink': {
      id: '/business/livelink'
      path: '/livelink'
      fullPath: '/business/livelink'
      preLoaderRoute: typeof BusinessLivelinkRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/history': {
      id: '/business/history'
      path: '/history'
      fullPath: '/business/history'
      preLoaderRoute: typeof BusinessHistoryRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/card': {
      id: '/business/card'
      path: '/card'
      fullPath: '/business/card'
      preLoaderRoute: typeof BusinessCardRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/gov/businesses/$ubid': {
      id: '/gov/businesses/$ubid'
      path: '/$ubid'
      fullPath: '/gov/businesses/$ubid'
      preLoaderRoute: typeof GovBusinessesUbidRouteImport
      parentRoute: typeof GovBusinessesRoute
    }
  }
}

interface BusinessRouteChildren {
  BusinessCardRoute: typeof BusinessCardRoute
  BusinessHistoryRoute: typeof BusinessHistoryRoute
  BusinessLivelinkRoute: typeof BusinessLivelinkRoute
  BusinessNoticesRoute: typeof BusinessNoticesRoute
  BusinessSubmitRoute: typeof BusinessSubmitRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessCardRoute: BusinessCardRoute,
  BusinessHistoryRoute: BusinessHistoryRoute,
  BusinessLivelinkRoute: BusinessLivelinkRoute,
  BusinessNoticesRoute: BusinessNoticesRoute,
  BusinessSubmitRoute: BusinessSubmitRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface GovBusinessesRouteChildren {
  GovBusinessesUbidRoute: typeof GovBusinessesUbidRoute
}

const GovBusinessesRouteChildren: GovBusinessesRouteChildren = {
  GovBusinessesUbidRoute: GovBusinessesUbidRoute,
}

const GovBusinessesRouteWithChildren = GovBusinessesRoute._addFileChildren(
  GovBusinessesRouteChildren,
)

interface GovRouteChildren {
  GovAlertsRoute: typeof GovAlertsRoute
  GovAuditRoute: typeof GovAuditRoute
  GovBusinessesRoute: typeof GovBusinessesRouteWithChildren
  GovLivelinkRoute: typeof GovLivelinkRoute
  GovMapRoute: typeof GovMapRoute
  GovQueryRoute: typeof GovQueryRoute
  GovReviewRoute: typeof GovReviewRoute
  GovIndexRoute: typeof GovIndexRoute
}

const GovRouteChildren: GovRouteChildren = {
  GovAlertsRoute: GovAlertsRoute,
  GovAuditRoute: GovAuditRoute,
  GovBusinessesRoute: GovBusinessesRouteWithChildren,
  GovLivelinkRoute: GovLivelinkRoute,
  GovMapRoute: GovMapRoute,
  GovQueryRoute: GovQueryRoute,
  GovReviewRoute: GovReviewRoute,
  GovIndexRoute: GovIndexRoute,
}

const GovRouteWithChildren = GovRoute._addFileChildren(GovRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRouteWithChildren,
  GovRoute: GovRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
